image: tensorflow/serving
port: 8501
models:
  id: ... # Add your model ID from step 1 here. The model ID can be seen under the Models tab in the Gradient GUI.
  path: "/opt/models/trained-model/"
env:
  - name: MODEL_BASE_PATH
    value: /opt/models/trained-model/
  - name: MODEL_NAME
    value: trained-model
resources:
  replicas: 1
  instanceType: C4
