defaults:
  env:
    apiKey: secret:api_key
  resources:
    instance-type: C4
    
jobs:
  CloneRepo:
    outputs:
      repo:
        type: volume
    uses: git-checkout@v1
    with:
      url: https://github.com/elhamadjidi/paraphrasing.git
      
  TrainModel:
    env:
      MODEL_DIR: /trained-model/1
    resources:
      instance-type: P4000
    needs:
      - CloneRepo
    inputs:
      repo: CloneRepo.outputs.repo
    outputs:
      trained-model:
        type: dataset
        with:
          ref: text-genie
    uses: script@v1
    with:
      script: |-
        pip install --upgrade pip
        pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cpu
        pip install transformers==4.10.2
        pip install sentencepiece==0.1.96
        cd /inputs/repo
        python train.py
        echo ls /
        ls /
        echo ls /trained_model
        ls /trained_model
        echo ls /trained_model/1
        ls /trained_model/1
        echo ls /trained_model/1/models
        ls /trained_model/1/models
        cp -R ./trained-model /outputs/trained-model
      image: tensorflow/tensorflow:1.14.0-gpu-py3
      
  UploadModel:
    inputs:
      model: TrainModel.outputs.trained-model
    outputs:
      model-id:
        type: string
    needs:
      - TrainModel
    uses: create-model@v1
    with:
      name: trained-model
      type: ONNX
