jobs:
  CloneRepo:
    resources:
      instance-type: C5
    outputs:
      repo:
        type: volume
    uses: git-checkout@v1
    with:
      url: https://github.com/NVlabs/stylegan2.git
  StyleGan2:
    resources:
      instance-type: P4000
    needs:
      - CloneRepo
    inputs:
      repo: CloneRepo.outputs.repo
    outputs:
      repo:
        type: volume
        with:
          ref: dsree0o3r64dzhg
    uses: script@v1
    with:
      script: |-
        pip install transformers==4.10.2
        pip install sentencepiece==0.1.96
        cd /inputs/repo
        python train.py
        cp -R /trained-model /outputs/trained-model
      image: tensorflow/tensorflow:1.14.0-gpu-py3
  UploadModel:
    inputs:
      model: TrainModel.outputs.trained-model
    outputs:
      model-id:
        type: string
    needs:
      - TrainModel
    uses: create-model@v1
    with:
      name: trained-model
      type: Tensorflow
